project:
  type: website

website:
  title: "Schäfer Lab"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: codes.qmd
        text: Codes
      #- href: funding.qmd
      #  text: Funding
      - href: theses.qmd
        text: Theses available
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: flatly
    css: styles.css
    toc: false